AZURE_LOCATION: 'eastus'
RESOURCE_NAME_PREFIX: 'drjtestapimlz'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'apim-demo-deployment'
VM_USERNAME: 'danjohn1234'
ACCOUNT_NAME: 'none'
CICD_AGENT_TYPE: 'none'
CERT_TYPE: 'selfsigned'
